#!/bin/bash
echo "Current GPU instance limits:"
echo "G and VT Spot Instance Requests: 0 vCPUs (need 4 for g4dn.xlarge)"
echo ""
echo "Please visit: https://console.aws.amazon.com/servicequotas/home/services/ec2/quotas"
echo "1. Search for 'Running On-Demand G and VT instances'"
echo "2. Request increase to 8 vCPUs (allows 2 instances)"
echo "3. Business justification: 'ML demo for academic research project'"
echo ""
echo "This usually takes 15-30 minutes to approve."
