model:
  weights: "models/weights/best.onnx"
  confidence_threshold: 0.7
  device: "mps"
  task: "detect"

classes:
  0: "person"
  1: "car"

output:
  save_predictions: true
  output_dir: "outputs/mapping"
  coordinate_system: "world"
